name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - sympy
  - scipy
  - matplotlib
  - slycot
  - control
  - graphviz
  - pip:
    - pysfg
    - graphviz
    - strictyaml
    - networkx
